---

fonts_path: /n/groups/winston/jc459/spn1/paper_figures/fonts
theme_path: scripts/spn1_2020_theme.R

spn1_depletion_western:
    spn1_blot: ../spn1-small-data/spn1_depletion_western/Spn1_depletion_Spn1_9.5.tif
    pgk1_blot: ../spn1-small-data/spn1_depletion_western/Spn1_depletion_Pgk1_for_Spn1_9_rot_2.2.tif
    quant_data: ../spn1-small-data/spn1_depletion_western/spn1_depletion_spn1_western_quantification.tsv
    fig_width: "11.4 * 2 / 12"
    fig_height: "9 / 16 * 11.4 * 8 / 12"
    panel_letter: a

spn1_depletion_chipseq_barplot:
    data: ../chipseq-spn1/qual_ctrl/spikein/Spn1-chipseq_spikein-counts.tsv
    fig_width: 3.5
    fig_height: 4
    panel_letter: c

spn1_depletion_metagene:
    data: ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-Spn1.tsv.gz
    fig_width: "11.4 * 8 / 12"
    fig_height: "9 / 16 * 11.4 * 8 / 12"
    panel_letter: b

spn1_depletion_figure:
    fig_width: 11.4
    fig_height: "9 / 16 * 11.4 * 8 / 12"

spn1_depletion_viability:
    data: ../spn1-small-data/spn1_depletion_viability/viability_data.txt
    fig_width: 8.5
    fig_height: "9 / 16 * 8.5"
    panel_letter: a

spn1_depletion_supplemental:
    fig_width: 17.4
    fig_height: "9 / 16 * 17.4 / 2"

rnaseq_maplot:
    data: ../rna-seq/diff_exp/verified-coding-genes/Spn1-IAA-v-Spn1-DMSO/spikenorm/Spn1-IAA-v-Spn1-DMSO_rnaseq-spikenorm-verified-coding-genes-diffexp-results-all.tsv
    fig_width: 8.5
    fig_height: "9 / 16 * 8.5"
    panel_letter: a

rnaseq_single_locus_datavis:
    data:
        SER3: ../spn1-data-integration/browser-shots/SER3/SER3_all-assays.tsv.gz
        UBI4: ../spn1-data-integration/browser-shots/UBI4/UBI4_all-assays.tsv.gz
        KAP120: ../spn1-data-integration/browser-shots/KAP120/KAP120_all-assays.tsv.gz
        GCV3: ../spn1-data-integration/browser-shots/GCV3/GCV3_all-assays.tsv.gz
    transcript_annotation: /n/groups/winston/jc459/intragenic/genome/annotations/Scer_polIItranscripts-adjustedTSS.bed
    orf_annotation: /n/groups/winston/jc459/intragenic/genome/annotations/Scer_nondubious_ORFs_and_blocked_reading_frames-adjustedATG.bed
    fig_width: "17.4 / 2"
    fig_height: "7 / 12 * 12"
    panel_letter: b

rpb1_metagenes:
    rpb1: ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-Rpb1.tsv.gz
    modifications:
        - ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-Ser5P-Rpb1norm.tsv.gz
        - ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-Ser2P-Rpb1norm.tsv.gz
    fig_width: 8.5
    fig_height: 8
    panel_letter: c

rnaseq_vs_rpb1:
    rnaseq: ../rna-seq/diff_exp/verified-coding-genes/Spn1-IAA-v-Spn1-DMSO/spikenorm/Spn1-IAA-v-Spn1-DMSO_rnaseq-spikenorm-verified-coding-genes-diffexp-results-all.tsv
    rpb1: ../chipseq-rpb1/diff_binding/verified-coding-genes/depleted-v-non-depleted/libsizenorm/depleted-v-non-depleted_Rpb1-chipseq-libsizenorm-verified-coding-genes-diffbind-results-all.tsv
    fig_width: 8.5
    fig_height: "9 / 16 * 8.5"
    panel_letter: d

rnaseq_rpb1_figure:
    fig_width: 17.4
    fig_height: 12

differential_expression_rtqpcr:
    data: ../spn1-small-data/differential_expression_rtqpcr/DE_rtqpcr_data.txt
    rnaseq: ../rna-seq/diff_exp/transcripts/Spn1-IAA-v-Spn1-DMSO/spikenorm/genic/Spn1-IAA-v-Spn1-DMSO_rnaseq-spikenorm-transcripts-diffexp-results-genic-all.tsv
    fig_width: 8.5
    fig_height: "9 / 16 * 8.5"
    panel_letter: a

antisense_single_locus_datavis:
    data:
        RRP1: ../spn1-data-integration/browser-shots/RRP1/RRP1_all-assays.tsv.gz
        MET10: ../spn1-data-integration/browser-shots/MET10/MET10_all-assays.tsv.gz
        ARO80: ../spn1-data-integration/browser-shots/ARO80/ARO80_all-assays.tsv.gz
        MAF1: ../spn1-data-integration/browser-shots/MAF1/MAF1_all-assays.tsv.gz
    transcript_annotation: ../custom_differential_expression/merged_transcripts/custom_diffexp_experimental-merged-transcripts-annotated.bed
    orf_annotation: /n/groups/winston/jc459/intragenic/genome/annotations/Scer_nondubious_ORFs_and_blocked_reading_frames-adjustedATG.bed
    fig_width: "17.4 / 2"
    fig_height: 9
    panel_letter: b

chipseq_abundance_barplots_rpb1:
    data:
        Rpb1: ../chipseq-rpb1/qual_ctrl/spikein/Rpb1-chipseq_spikein-counts.tsv
        Rpb1-Ser5P: ../chipseq-ser5p/qual_ctrl/spikein/Ser5P-chipseq_spikein-counts.tsv
        Rpb1-Ser2P: ../chipseq-ser2p/qual_ctrl/spikein/Ser2P-chipseq_spikein-counts.tsv
    fig_width: "17.4 * 5 / 12"
    fig_height: 5
    panel_letter: c

rnaseq_rpb1_supplemental:
    fig_width: 17.4
    fig_height: 8


splicing:
    data: ../custom_figures/figures/intron_retention/Spn1-IAA-v-all-controls_intron_retention_results.tsv
    aliases: /n/groups/winston/jc459/intragenic/genome/Scer-sys-to-common-name.tsv
    rp_genes: ../genome/annotations/gene_lists/Scer_RPgene_transcripts.bed
    fig_width: "17.4/2"
    fig_height: 9
    panel_letter: a

splicing_rtqpcr:
    data: ../spn1-small-data/splicing_rtqpcr/IR_rtqpcr_data.txt
    fig_width: 8.5
    fig_height: "9 / 16 * 8.5"
    panel_letter: b

splicing_figure:
    fig_width: 8.5
    fig_height: 8

promoter_swap_diagram:
    data: ../spn1-small-data/promoter_swap_rtqpcr/promoter_swap_diagram.tsv
    fig_width: 8.5
    fig_height: "9 / 16 * 8.5"
    panel_letter: a

promoter_swap_rtqpcr:
    data: ../spn1-small-data/promoter_swap_rtqpcr/promoter_swap_rtqpcr_data.txt
    rnaseq: ../rna-seq/diff_exp/transcripts/Spn1-IAA-v-Spn1-DMSO/spikenorm/genic/Spn1-IAA-v-Spn1-DMSO_rnaseq-spikenorm-transcripts-diffexp-results-genic-all.tsv
    fig_width: 8.5
    fig_height: "9 / 16 * 8.5"
    panel_letter: b

promoter_swap_figure:
    fig_width: 8.5
    fig_height: 8

coip_western:
    input_rpb3_blot: ../spn1-small-data/coip_westerns/Rpb3-Flag WB Rep1 inputs_10.tif
    input_spt6_blot: ../spn1-small-data/coip_westerns/Spt6 WB Rep1 inputs_8.tif
    input_spn1_blot: ../spn1-small-data/coip_westerns/Spn1 WB Rep1 inputs_8.5_2.tif
    input_set2_blot: ../spn1-small-data/coip_westerns/Set2 WB Rep3 inputs_8-4.tif
    ip_rpb3_blot: ../spn1-small-data/coip_westerns/Rpb3-Flag WB Rep1 IPs_9.tif
    ip_spt6_blot: ../spn1-small-data/coip_westerns/Spt6 WB Rep1 IPs_7.5.tif
    ip_spn1_blot: ../spn1-small-data/coip_westerns/Spn1 WB Rep1 IPs_8_3.tif
    ip_set2_blot: ../spn1-small-data/coip_westerns/Set2 WB Rep2 IPs_8-7.tif
    fig_width: 11.4
    fig_height: "9 / 16 * 8.5"
    panel_letter: a

set2_metagene:
    data: ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-Set2.tsv.gz
    fig_width: 8.5
    fig_height: "9 / 16 * 8.5"
    panel_letter: d

spt6_metagene:
    data: ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-Spt6.tsv.gz
    fig_width: 8.5
    fig_height: "9 / 16 * 8.5"
    panel_letter: b

set2_abundance_chipseq_barplot:
    data: ../chipseq-set2/qual_ctrl/spikein/Set2-chipseq_spikein-counts.tsv
    fig_width: 3.5
    fig_height: 4
    panel_letter: e

spt6_abundance_chipseq_barplot:
    data: ../chipseq-spt6/qual_ctrl/spikein/Spt6-chipseq_spikein-counts.tsv
    fig_width: 3.5
    fig_height: 4
    panel_letter: c

set2_spt6_figure:
    fig_width: 11.4
    fig_height: 13

h3_vs_rpb1_ma:
    h3: ../chipseq-h3/diff_binding/verified-coding-genes/depleted-v-non-depleted/libsizenorm/depleted-v-non-depleted_H3-chipseq-libsizenorm-verified-coding-genes-diffbind-results-all.tsv
    rpb1: ../chipseq-rpb1/diff_binding/verified-coding-genes/depleted-v-non-depleted/libsizenorm/depleted-v-non-depleted_Rpb1-chipseq-libsizenorm-verified-coding-genes-diffbind-results-all.tsv
    fig_width: 8.5
    fig_height: "9 / 16 * 8.5"
    panel_letter: a

reduced_h3_h3_metagene:
    data:
        - ../spn1-data-integration/datavis/plmin-reduced-H3/plmin-reduced-H3_ChIPseq-H3.tsv.gz
    fig_width: 8.5
    fig_height: "9 / 16 * 8.5"
    panel_letter: b

h3_single_locus_datavis:
    data:
        GLY1: ../spn1-data-integration/browser-shots/GLY1/GLY1_all-assays.tsv.gz
        RPL28: ../spn1-data-integration/browser-shots/RPL28/RPL28_all-assays.tsv.gz
    transcript_annotation: /n/groups/winston/jc459/intragenic/genome/annotations/Scer_transcripts_w_verifiedORFs.bed
    orf_annotation: /n/groups/winston/jc459/intragenic/genome/annotations/Scer_nondubious_ORFs_and_blocked_reading_frames-adjustedATG.bed
    fig_width: 8.5
    fig_height: "9 / 16 * 8.5"
    panel_letter: c

h3_figure:
    fig_width: 8.5
    fig_height: 12

h3_metagene:
    data:
        - ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-H3.tsv.gz
    fig_width: "17.4 / 2"
    fig_height: "17.4 / 2 * 9 / 16"
    panel_letter: b

h3_modification_datavis:
    data:
        - ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-H3K4me3-H3norm.tsv.gz
        - ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-H3K36me2-H3norm.tsv.gz
        - ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-H3K36me3-H3norm.tsv.gz
    annotation: /n/groups/winston/jc459/intragenic/genome/annotations/Scer_transcripts_w_verifiedORFs-nonoverlapping.bed
    fig_width: 17.4
    fig_height: 12
    panel_letter: a

h3_mods_figure:
    fig_width: 17.4
    fig_height: 11
