---

fonts_path: /n/groups/winston/jc459/spn1/paper_figures/fonts
theme_path: scripts/spn1_2020_theme.R

spn1_depletion_metagene:
    data: ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-Spn1.tsv.gz
    fig_width: "11.4 * 8 / 12"
    fig_height: "9 / 16 * 11.4 * 8 / 12"
    panel_letter: c

spn1_depletion_figure:
    fig_width: 11.4
    fig_height: "9 / 16 * 11.4 * 8 / 12"

spn1_depletion_chipseq_barplot:
    data: ../chipseq-spn1/qual_ctrl/spikein/Spn1-chipseq_spikein-counts.tsv
    fig_width: 3.5
    fig_height: 4
    panel_letter: b

rnaseq_maplot:
    data: ../rna-seq/diff_exp/verified-coding-genes/Spn1-IAA-v-Spn1-DMSO/spikenorm/Spn1-IAA-v-Spn1-DMSO_rnaseq-spikenorm-verified-coding-genes-diffexp-results-all.tsv
    fig_width: 8.5
    fig_height: "9 / 16 * 8.5"
    panel_letter: a

rpb1_metagenes:
    data:
        - ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-Rpb1.tsv.gz
        - ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-Ser5P-Rpb1norm.tsv.gz
        - ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-Ser2P-Rpb1norm.tsv.gz
    fig_width: 8.5
    fig_height: 8
    panel_letter: x

histone_metagenes:
    data:
        - ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-H3.tsv.gz
        - ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-H3K4me3-H3norm.tsv.gz
        - ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-H3K36me2-H3norm.tsv.gz
        - ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-H3K36me3-H3norm.tsv.gz
    fig_width: 8.5
    fig_height: 12
    panel_letter: x

