---

fonts_path: /n/groups/winston/jc459/spn1/paper_figures/fonts
theme_path: scripts/spn1_2020_theme.R

spn1_depletion_western:
    spn1_blot: ../spn1-small-data/spn1_depletion_western/Spn1_depletion_Spn1_9.5.tif
    pgk1_blot: ../spn1-small-data/spn1_depletion_western/Spn1_depletion_Pgk1_for_Spn1_9.tif
    fig_width: "11.4 * 2 / 12"
    fig_height: "9 / 16 * 11.4 * 8 / 12"
    panel_letter: a

spn1_depletion_chipseq_barplot:
    data: ../chipseq-spn1/qual_ctrl/spikein/Spn1-chipseq_spikein-counts.tsv
    fig_width: 3.5
    fig_height: 4
    panel_letter: b

spn1_depletion_metagene:
    data: ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-Spn1.tsv.gz
    fig_width: "11.4 * 8 / 12"
    fig_height: "9 / 16 * 11.4 * 8 / 12"
    panel_letter: c

spn1_depletion_figure:
    fig_width: 11.4
    fig_height: "9 / 16 * 11.4 * 8 / 12"

spn1_depletion_viability:
    data: ../spn1-small-data/spn1_depletion_viability/viability_total_col_per_mL_rel_T0.txt
    fig_width: 6
    fig_height: "9 / 16 * 6"
    panel_letter: x




rnaseq_maplot:
    data: ../rna-seq/diff_exp/verified-coding-genes/Spn1-IAA-v-Spn1-DMSO/spikenorm/Spn1-IAA-v-Spn1-DMSO_rnaseq-spikenorm-verified-coding-genes-diffexp-results-all.tsv
    fig_width: 8.5
    fig_height: "9 / 16 * 8.5"
    panel_letter: a

rpb1_metagenes:
    rpb1: ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-Rpb1.tsv.gz
    modifications:
        - ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-Ser5P-Rpb1norm.tsv.gz
        - ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-Ser2P-Rpb1norm.tsv.gz
    fig_width: 8.5
    fig_height: 8
    panel_letter: c

rnaseq_vs_rpb1:
    rnaseq: ../rna-seq/diff_exp/verified-coding-genes/Spn1-IAA-v-Spn1-DMSO/spikenorm/Spn1-IAA-v-Spn1-DMSO_rnaseq-spikenorm-verified-coding-genes-diffexp-results-all.tsv
    rpb1: ../chipseq-rpb1/diff_binding/verified-coding-genes/depleted-v-non-depleted/libsizenorm/depleted-v-non-depleted_Rpb1-chipseq-libsizenorm-verified-coding-genes-diffbind-results-all.tsv
    fig_width: 8.5
    fig_height: "9 / 16 * 8.5"
    panel_letter: d

rnaseq_rpb1_figure:
    fig_width: 17.4
    fig_height: 12

promoter_swap_rtqpcr:
    data: ../spn1-small-data/promoter_swap_rtqpcr/promoter_swap_rtqpcr_data.txt
    rnaseq: ../rna-seq/diff_exp/transcripts/Spn1-IAA-v-Spn1-DMSO/spikenorm/genic/Spn1-IAA-v-Spn1-DMSO_rnaseq-spikenorm-transcripts-diffexp-results-genic-all.tsv
    fig_width: 8.5
    fig_height: "9 / 16 * 8.5"
    panel_letter: b

promoter_swap_figure:
    fig_width: 8.5
    fig_height: "9 / 16 * 8.5 * 2"

set2_metagene:
    data: ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-Set2.tsv.gz
    fig_width: 8.5
    fig_height: "9 / 16 * 8.5"
    panel_letter: b

spt6_metagene:
    data: ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-Spt6.tsv.gz
    fig_width: 8.5
    fig_height: "9 / 16 * 8.5"
    panel_letter: d

set2_abundance_chipseq_barplot:
    data: ../chipseq-set2/qual_ctrl/spikein/Set2-chipseq_spikein-counts.tsv
    fig_width: 3.5
    fig_height: 4
    panel_letter: c

spt6_abundance_chipseq_barplot:
    data: ../chipseq-spt6/qual_ctrl/spikein/Spt6-chipseq_spikein-counts.tsv
    fig_width: 3.5
    fig_height: 4
    panel_letter: e

set2_spt6_figure:
    fig_width: 8.5
    fig_height: 13


h3_metagene:
    data:
        - ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-H3.tsv.gz
    fig_width: "17.4 / 2"
    fig_height: "17.4 / 2 * 9 / 16"
    panel_letter: a

h3_modification_datavis:
    data:
        - ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-H3K4me3-H3norm.tsv.gz
        - ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-H3K36me2-H3norm.tsv.gz
        - ../spn1-data-integration/datavis/verified-transcripts-nonoverlapping-TSS/verified-transcripts-nonoverlapping-TSS_ChIPseq-H3K36me3-H3norm.tsv.gz
    annotation: /n/groups/winston/jc459/intragenic/genome/annotations/Scer_transcripts_w_verifiedORFs-nonoverlapping.bed
    fig_width: 17.4
    fig_height: 12
    panel_letter: c

h3_and_mods_figure:
    fig_width: 17.4
    fig_height: 14
